# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b495a3196651d1761f3402df0c7d4486de4fb5945c6be77a1f27e9b98206d5b4eb5e2def98d893d94fc23a6f1fd3665d4d9369cc2a599183b5094f0b8e0587b

test:
  secret_key_base: f25f6f4c5b77799fe9df2ed93afb591ac3366b973f9cbb8f055bb4ad866fe4e9e4310f8123920442ca5ec32802a464250dbb93113ededa5c33cadea6b6a4bc07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
